export const SET_PAGE_TAB_SELECT = 'SET_PAGE_TAB_SELECT';
export const SET_LOTTERY_KEY = 'SET_LOTTERY_KEY';
export const SET_LOTTERY_LIST = 'SET_LOTTERY_LIST';
export const SET_HOT_LOTTERY_LIST = 'SET_HOT_LOTTERY_LIST';
