server:
  port: 23101
  servlet:
    context-path: /ucenter

spring:
  profiles:
    active: test
  application:
    name: hm2-service-user

  #日志相关//无特殊要求，使用根目录下配置
logback:
  logFileDir: user
logging:
  config: classpath:logback-spring.xml
