spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.244.55.58:3306/hm_logs
    username: hm2
    password: aa123456
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      connection-timeout: 5000
      idle-timeout: 60000
      max-lifetime: 60000
  redis:
    database: 10
    host: 103.244.55.58
    port: 6379
    password: hm@123456
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10000 #连接池最大等行时间 -1没有限制
  cloud:
    nacos:
      discovery:
        namespace: 9929e47f-6454-4766-bdba-de6b723f772c
        server-addr: ${nacos.server-addr}  #注册地址
        metadata:
          group: discovery-gray-group
          version: 1.0
    #网关路由转发
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: hm2-service-auth
          uri: lb://hm2-service-auth
          predicates:
            - Path=/v2/auth/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
        - id: hm2-service-user
          uri: lb://hm2-service-user
          predicates:
            - Path=/v2/ucenter/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
        - id: hm2-service-ctrl
          uri: lb://hm2-service-ctrl
          predicates:
            - Path=/v2/ctrl/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
        - id: hm2-service-result-receive
          uri: lb://hm2-service-result-receive
          predicates:
            - Path=/v2/result/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
        - id: hm2-service-member
          uri: lb://hm2-service-member
          predicates:
            - Path=/v2/mem/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
        - id: hm2-service-order
          uri: lb://hm2-service-order
          predicates:
            - Path=/v2/order/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
        - id: hm2-service-logs
          uri: lb://hm2-service-logs
          predicates:
            - Path=/v2/logs/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
        - id: hm2-server-smart-bet
          uri: lb://hm2-server-smart-bet
          predicates:
            - Path=/v2/smart/**
          filters:
            - StripPrefix=1  #去掉前缀，数值代表去掉多少
nacos:
  server-addr: 43.252.170.248:8848