spring:
  redis:
    database: 10
    host: 103.244.55.58
    port: 6379
    password: hm@123456
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10000 #连接池最大等行时间 -1没有限制
  cloud:
    nacos:
      discovery:
        namespace: 9929e47f-6454-4766-bdba-de6b723f772c
        server-addr: ${nacos.server-addr}
        metadata:
          group: discovery-guide-group
          version: 1.0
          region: ${nacos.region}
dubbo:
  cloud:
    subscribed-services: hm2-service-user
  consumer:
    check: false
#是否开启图片验证
auth:
  captcha-enabled: false

nacos:
  server-addr: 43.252.170.248:8848
  region: ${spring.profiles.active}