server:
  port: 23201
  servlet:
    context-path: /order

spring:
  profiles:
    active: test
  application:
    name: hm2-service-order
  task:
    scheduling:
      pool:
        size: 30

#日志相关//无特殊要求，使用根目录下配置
logback:
  logFileDir: order
logging:
  config: classpath:logback-spring.xml
