spring:
  cloud:
    nacos:
      discovery:
        namespace: 73f1cfcc-eedc-4e40-83b3-f1f3db148387
        server-addr: ${nacos.server-addr}
        metadata:
          group: discovery-gray-group
          version: 1.0
          region: ${nacos.region}
  redis:
    database: 6
    host: 103.244.55.58
    port: 6379
    password: hm@123456
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10000 #连接池最大等行时间 -1没有限制
tio:
  websocket:
    server:
      port: 24010
      heartbeat-timeout: 60000

dubbo:
  scan:
    base-packages: com.xzy.socket.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: hm2-websocket,hm2-service-ctrl
  provider:
    filter: -exception
    timeout: 10000
  consumer:
    check: false
    timeout: 10000

nacos:
  server-addr: 43.252.170.248:8848
  region: ${spring.profiles.active}
