server:
  port: 24000

spring:
  profiles:
    active: test
  application:
    name: hm2-websocket
  task:
    scheduling:
      pool:
        size: 30
  #日志相关//无特殊要求，使用根目录下配置
logback:
  logFileDir: websocket
logging:
  config: classpath:logback-spring.xml
